import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Política de privacidad",
  description: "Información sobre el tratamiento de datos personales en TecRural.",
};

const p = "text-tr-muted leading-relaxed";
const h2 = "mt-8 mb-3 font-heading font-semibold text-tr-forest text-xl";

export default function PrivacidadPage() {
  return (
    <main className="min-h-screen bg-tr-paper px-4 py-10">
      <article className="mx-auto max-w-3xl rounded-[var(--tr-radius-card)] border border-tr-line bg-tr-surface p-6 shadow-[var(--tr-shadow-card)] sm:p-10">
        <h1 className="font-heading text-3xl font-bold text-tr-forest">Política de privacidad</h1>
        <p className={`${p} mt-2`}>Última actualización: 3 de octubre de 2026</p>
        <h2 className={h2}>1. Responsable del tratamiento</h2>
        <p className={p}>Responsable: <strong>Manuel Carrasco García</strong>. NIF: <strong>76143911L</strong>. Domicilio: <strong>Barrio Los Reyes 113, 18830 Huéscar (Granada), España</strong>. Contacto: <a className="underline" href="mailto:mcgnexus@gmail.com">mcgnexus@gmail.com</a>. No consta designación de delegado de protección de datos.</p>
        <h2 className={h2}>2. Datos tratados y procedencia</h2>
        <p className={p}>Según cómo uses el servicio, podemos tratar las siguientes categorías de datos: (a) <strong>datos de contacto de la solicitud de revisión</strong>: nombre (si lo facilitas), teléfono, municipio, cultivo, síntomas y mensajes, la forma de contacto elegida y, si los adjuntas, fotografías; (b) <strong>datos del diagnóstico</strong>: la orientación generada y el contexto agronómico declarado (cultivo, zona, síntoma, variedad); (c) <strong>datos de navegación y campaña</strong>, como los parámetros UTM del enlace de entrada; (d) <strong>datos técnicos de uso</strong>: un identificador de visitante en cookie, la dirección IP y la marca de tiempo, empleados para aplicar los límites de uso y medir visitas de forma agregada; y (e) <strong>teléfono para ampliar la cuota</strong>, tratado únicamente como se explica en la sección 9. Los datos de contacto y las fotografías los proporcionas tú; los datos técnicos de uso se generan automáticamente al utilizar el sitio.</p>
        <h2 className={h2}>3. Finalidades y base jurídica</h2>
        <p className={p}>Usamos los datos para las siguientes finalidades, cada una con su base jurídica: (a) <strong>gestionar y atender la solicitud de revisión</strong> y responder por el canal elegido, sobre la base de atender las medidas solicitadas por la persona interesada antes de una posible relación contractual (art. 6.1.b RGPD); (b) <strong>aplicar los límites de uso y prevenir el abuso del servicio</strong>, incluida la ampliación de cuota mediante teléfono de la sección 9, sobre la base del interés legítimo del responsable en contener el coste de las llamadas a los proveedores de IA y evitar usos fraudulentos (art. 6.1.f RGPD); (c) <strong>medir visitas y conversión de forma agregada y sin identificarte</strong>, sobre la base del mismo interés legítimo; y (d) <strong>enviar comunicaciones comerciales</strong> por WhatsApp, solo si marcas la casilla opcional correspondiente, sobre la base de tu consentimiento separado (art. 6.1.a RGPD); retirarlo no afecta a la solicitud de revisión.</p>
        <h2 className={h2}>4. Fotografías y contexto del cultivo</h2>
        <p className={p}>Las imágenes del análisis solo se envían al servicio cuando se presenta una solicitud de revisión que las adjunta, para que el técnico pueda revisar ese caso. Pueden mostrar información del estado y ubicación aproximada de una explotación o cultivo; evita incluir personas, documentos u otros datos que no sean necesarios. Las imágenes adjuntas se guardan junto al registro de la solicitud en la base de datos y se eliminarán como máximo a los 12 meses desde el envío. El responsable debe revisar mensualmente los registros vencidos y borrar las imágenes de la base de datos. También puedes pedir su supresión anticipada escribiendo a <a className="underline" href="mailto:mcgnexus@gmail.com">mcgnexus@gmail.com</a>; se tramitará dentro del plazo legal aplicable.</p>
        <h2 className={h2}>5. Conservación</h2>
        <p className={p}>Las fotografías adjuntas se conservarán un máximo de 12 meses desde la fecha de envío de la solicitud. El responsable revisará mensualmente los registros vencidos y eliminará las imágenes de la base de datos; hasta completar esa revisión podrían permanecer almacenadas brevemente después del plazo. Los datos de la solicitud se conservarán mientras sean necesarios para atenderla y, posteriormente, durante los plazos necesarios para cumplir obligaciones legales o atender responsabilidades. Los datos de control de uso (sección 9) se conservan como máximo 180 días la huella del teléfono y 31 días los registros de uso con IP. Puedes solicitar acceso, rectificación o supresión escribiendo a <a className="underline" href="mailto:mcgnexus@gmail.com">mcgnexus@gmail.com</a>.</p>
        <h2 className={h2}>6. Destinatarios y proveedores</h2>
        <p className={p}>Para prestar el servicio se utilizan proveedores tecnológicos: Neon (base de datos), Vercel (alojamiento/despliegue, si la aplicación se sirve desde esa plataforma), Google (Google Analytics cuando se configura y Google Gemini para análisis) y DeepSeek (análisis alternativo). Cuando se realiza un análisis, las imágenes y el contexto agronómico necesario pueden comunicarse al proveedor de inteligencia artificial que procese la solicitud. Estos proveedores pueden tratar datos desde fuera del Espacio Económico Europeo; en ese caso se aplicarán las garantías previstas por la normativa, como las cláusulas contractuales tipo cuando corresponda. El servicio también puede apoyarse en proveedores de correo o notificaciones configurados para la aplicación.</p>
        <h2 className={h2}>7. Derechos</h2>
        <p className={p}>Puedes solicitar acceso, rectificación, supresión, oposición, limitación o portabilidad, así como retirar el consentimiento comercial, escribiendo a <a className="underline" href="mailto:mcgnexus@gmail.com">mcgnexus@gmail.com</a>. También puedes reclamar ante la Agencia Española de Protección de Datos. Para tramitar la solicitud podremos pedir información razonable para verificar tu identidad. Como el teléfono de la sección 9 no se conserva en claro, la supresión consiste en eliminar la huella seudonimizada y su asociación con el dispositivo; si necesitas acreditarlo, indícanos el identificador que corresponda.</p>
        <h2 className={h2}>8. Comunicaciones comerciales</h2>
        <p className={p}>Solo se enviarán novedades comerciales si marcas la casilla opcional correspondiente. Puedes darte de baja en cualquier momento desde <Link className="underline" href="/baja">la página de baja</Link>.</p>
        <h2 id="limite-analisis" className={h2}>9. Ampliación del límite de análisis y control de uso</h2>
        <p className={p}><strong>Qué datos y para qué.</strong> Puedes realizar dos análisis sin facilitar datos de contacto. Si quieres ampliar el límite a seis análisis por cada periodo móvil de siete días, te pedimos un número de teléfono. Para asociar esa ampliación a tu dispositivo y evitar usos fraudulentos tratamos, además, un identificador de visitante guardado en una cookie técnica y datos técnicos de la conexión, como la dirección IP y la marca de tiempo de cada análisis. Esta finalidad es exclusivamente aplicar y hacer cumplir el límite de uso y prevenir el abuso del servicio, que tiene un coste por cada llamada a los proveedores de inteligencia artificial. Además del límite por dispositivo, aplicamos un <strong>límite complementario por conexión (IP)</strong> para frenar el uso automatizado o el reinicio del identificador; este límite es holgado para no perjudicar a varias personas que compartan una misma red.</p>
        <p className={p}><strong>Base jurídica.</strong> Tratamos estos datos sobre la base del interés legítimo del responsable en contener el coste del servicio y evitar usos fraudulentos (art. 6.1.f RGPD), ponderado con las garantías de minimización que se describen a continuación. La casilla que marcas antes de facilitar el teléfono no es un consentimiento para contactarte ni para enviarte publicidad: confirma únicamente que conoces esta finalidad.</p>
        <p className={p}><strong>Minimización y ausencia de otras finalidades.</strong> No guardamos el número de teléfono en claro. Almacenamos únicamente una huella seudonimizada (un HMAC-SHA-256 calculado con una clave secreta del servidor) que no permite reconstruir el número, asociada a tu identificador de dispositivo. No usamos el teléfono para contactarte, no lo cedemos con fines comerciales y no lo incorporamos al registro de solicitudes de revisión. Esta ampliación no constituye una solicitud de revisión técnica ni un consentimiento de comunicaciones comerciales. No se realizan decisiones automatizadas con efectos jurídicos sobre ti; el único efecto del control es permitir o denegar un análisis según la cuota.</p>
        <p className={p}><strong>Conservación.</strong> La huella del teléfono se conserva mientras sea necesaria para aplicar el límite y, como máximo, 180 días desde su vinculación. Los registros de uso para el control de límites, incluida la IP, se eliminan al superar los 31 días.</p>
        <p className={p}><strong>Destinatarios.</strong> La base de datos (Neon) y el alojamiento (Vercel) tratan estos datos como proveedores por cuenta del responsable. No se comunican a los proveedores de inteligencia artificial para esta finalidad. Pueden tratarse fuera del Espacio Económico Europeo con las garantías previstas por la normativa, como las cláusulas contractuales tipo cuando corresponda.</p>
        <p className={p}>Puedes oponerte a este tratamiento o solicitar la supresión de la vinculación escribiendo a <a className="underline" href="mailto:mcgnexus@gmail.com">mcgnexus@gmail.com</a>; ten en cuenta que, si te opones, no podremos aplicar la ampliación de cuota y el límite volverá a ser el anónimo.</p>
        <p className={`${p} mt-10 border-t border-tr-line pt-5 text-small`}><Link className="underline" href="/aviso-legal">Aviso legal</Link> · <Link className="underline" href="/cookies">Cookies</Link> · <Link className="underline" href="/contacto">Contacto</Link>.</p>
      </article>
    </main>
  );
}
